### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by z100233y** [malibio/msi-z590i-unify-opencore#1]
How long can the boss finish the configuration? Thank you very much

**Comment by malibio** [comment]
Please give me until the weekend to prepare things. I still need to clean my config file and provide some basic instructions.

**Comment by malibio** [comment]
OK...for now, I"ve uploaded the EFI contents. You just now need to read up on how to create the install files yourself (using the EFI folder I shared. If you can wait a little longer, I'll update the readme file to include a short guide.

I hope it helps.

**Comment by Sizukaze** [comment]
> OK...for now, I"ve uploaded the EFI contents. You just now need to read up on how to create the install files yourself (using the EFI folder I shared. If you can wait a little longer, I'll update the readme file to include a short guide.
> 
> I hope it helps.

Thank you very much! Waiting for you to release a detailed tutorial

**Comment by malibio** [comment]
Hey there...sorry for the overdue clean up and instructions. I'm happy to tell you that I have indeed (finally) gotten around to doing so. Have a look.
