### ISSUE TITLE
thanks! works perfect

### ISSUE THREAD

**Issue by qixiang109** [malibio/msi-z590i-unify-opencore#2]
This efi works for me, it suits perfectly smooth with macos 12.3 monterey and opencore 0.79. Other guides I found does not. Thank you malibio !

**Comment by Submergence2000** [comment]
Pretty incredible work!
I'm thinking about buying this motherboard, and I want to know whether the sleep/wake works well in MacOS?
Thx.

**Comment by malibio** [comment]
Thanks for the feedback. I've cleaned up the EFI a lot. Please have a look and provide feedback (if it works or not, etc.)

**Comment by malibio** [comment]
> Pretty incredible work!
> I'm thinking about buying this motherboard, and I want to know whether the sleep/wake works well in MacOS?
> Thx.

Sleep/wake works, but you need to use the power button for wake (vs keyboard/mouse).
