### ISSUE TITLE
TB3/4 

### ISSUE THREAD

**Issue by ChopperD00** [malibio/msi-z590i-unify-opencore#3]
Greetings,

Excellent work here, I have the exact same setup sort of the CPU. I have an 10900K. I haven't gotten the TB to work... I ended up using a TB3 ssdt from an old efi build, but loved how clean your setup was as opposed to what my original build was. 

I don't see anything in my system report under TB or PCI, so I was wondering if that was the same for you, as I suspect that it's just seeing the port as a USB one.

Thanks much and excellent work!

P

**Comment by malibio** [comment]
It's the same for me. I don't see anything under Thunderbolt/USB4.
To be honest, I cannot verify if hot-plug is even working. I would have to get a device to really try it out. Let us know if you get any luck with it.

Also, one thing to note: my build is a Z590 board (thus the 11700K CPU). With a 10900K, I can assume you've got a Z490. I don't know if my EFI would work there. One thing for sure, I've had to emulate my CPU. With a 10th gen CPU like yours, you wouldn't needed. If you know all this already, sorry for repeating myself :-)

Enjoy!

**Comment by ChopperD00** [comment]
any issues with dual boot win 11 at all? got everything up, but that.

**Comment by malibio** [comment]
No issues...works practically right out of the box for me. I actually have Windows [installed on a USB drive](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-to-go-overview). So, if I leave it plugged in (during boot), the open core bootloader automatically makes it an option for me to boot into. I imagine it would work the same way, when having it in a separate partition.

If I had to build my system on the same hard drive, I would build my Windows system first, then create/install the macOS system after. I believe if you install macOS first, the Windows boot file (EFI) will later replace or prepend the macOS EFI.

**Comment by ChopperD00** [comment]
I thought that as well... my original install worked out that way... i think i may have a config issue that i have to comb over. That being said... this time around on this clean wipe i did Mac then Windows instead of the other way around.
